# Generated by Django 3.0.8 on 2020-07-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedmessage',
            name='review_date',
            field=models.DateTimeField(null=True),
        ),
    ]
