# Generated by Django 3.0.8 on 2020-07-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identifier', '0002_auto_20200728_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedmessage',
            name='is_safe',
            field=models.BooleanField(null=True),
        ),
    ]
